package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExArrangement generated by hbm2java
 */
@DataTransferObject
public class ExArrangement  implements java.io.Serializable {


     private String id;
     private ExInstitution exInstitution;
     private ExLanguage exLanguage;
     private ExSection exSection;
     private ExPhysicexamroom exPhysicexamroom;
     private String startexamnum;
     private String endexamnum;
     private Set exStudentsForTheoryarrangeid = new HashSet(0);

     private Set exStudentsForOperatearrangeid = new HashSet(0);
     private Set exArrangeSupervisors = new HashSet(0);

    public ExArrangement() {
    }

	
    public ExArrangement(String id) {
        this.id = id;
    }
    public ExArrangement(String id, ExInstitution exInstitution, ExLanguage exLanguage, ExSection exSection, ExPhysicexamroom exPhysicexamroom, String startexamnum, String endexamnum, Set exStudentsForTheoryarrangeid, Set exStudentsForOperatearrangeid,Set exArrangeSupervisors) {
       this.id = id;
       this.exInstitution = exInstitution;
       this.exLanguage = exLanguage;
       this.exSection = exSection;
       this.exPhysicexamroom = exPhysicexamroom;
       this.startexamnum = startexamnum;
       this.endexamnum = endexamnum;
       this.exStudentsForTheoryarrangeid = exStudentsForTheoryarrangeid;
     
       this.exStudentsForOperatearrangeid = exStudentsForOperatearrangeid;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    public ExLanguage getExLanguage() {
        return this.exLanguage;
    }
    
    public void setExLanguage(ExLanguage exLanguage) {
        this.exLanguage = exLanguage;
    }
    public ExSection getExSection() {
        return this.exSection;
    }
    
    public void setExSection(ExSection exSection) {
        this.exSection = exSection;
    }
    public ExPhysicexamroom getExPhysicexamroom() {
        return this.exPhysicexamroom;
    }
    
    public void setExPhysicexamroom(ExPhysicexamroom exPhysicexamroom) {
        this.exPhysicexamroom = exPhysicexamroom;
    }
    public String getStartexamnum() {
        return this.startexamnum;
    }
    
    public void setStartexamnum(String startexamnum) {
        this.startexamnum = startexamnum;
    }
    public String getEndexamnum() {
        return this.endexamnum;
    }
    
    public void setEndexamnum(String endexamnum) {
        this.endexamnum = endexamnum;
    }
    public Set getExStudentsForTheoryarrangeid() {
        return this.exStudentsForTheoryarrangeid;
    }
    
    public void setExStudentsForTheoryarrangeid(Set exStudentsForTheoryarrangeid) {
        this.exStudentsForTheoryarrangeid = exStudentsForTheoryarrangeid;
    }

    public Set getExStudentsForOperatearrangeid() {
        return this.exStudentsForOperatearrangeid;
    }
    
    public void setExStudentsForOperatearrangeid(Set exStudentsForOperatearrangeid) {
        this.exStudentsForOperatearrangeid = exStudentsForOperatearrangeid;
    }
    
    public Set getExArrangeSupervisors(){
    	return this.exArrangeSupervisors;
    }
    public Set setExArrangeSupervisors(Set exArrangeSupervisors){
    	return this.exArrangeSupervisors;
    }
}


