package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExCampus generated by hbm2java
 */
@DataTransferObject
public class ExCampus  implements java.io.Serializable {


     private String id;
     private ExInstitution exInstitution;
     private String campusnum;
     private String name;
     private String remark;
     private Set exStudents = new HashSet(0);
     private Set exPhysicexamrooms = new HashSet(0);

    public ExCampus() {
    }

	
    public ExCampus(String id) {
        this.id = id;
    }
    public ExCampus(String id, ExInstitution exInstitution, String campusnum, String name, String remark, Set exStudents, Set exPhysicexamrooms) {
       this.id = id;
       this.exInstitution = exInstitution;
       this.campusnum = campusnum;
       this.name = name;
       this.remark = remark;
       this.exStudents = exStudents;
       this.exPhysicexamrooms = exPhysicexamrooms;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    public String getCampusnum() {
        return this.campusnum;
    }
    
    public void setCampusnum(String campusnum) {
        this.campusnum = campusnum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getExStudents() {
        return this.exStudents;
    }
    
    public void setExStudents(Set exStudents) {
        this.exStudents = exStudents;
    }
    public Set getExPhysicexamrooms() {
        return this.exPhysicexamrooms;
    }
    
    public void setExPhysicexamrooms(Set exPhysicexamrooms) {
        this.exPhysicexamrooms = exPhysicexamrooms;
    }




}


