package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExCollege generated by hbm2java
 */
@DataTransferObject
public class ExCollege  implements java.io.Serializable {


     private String id;
     private String collegenum;
     private String name;
     private String remark;
     private ExInstitution exInstitution;
     private Set exStudents = new HashSet(0);

    public ExCollege() {
    }

	
    public ExCollege(String id) {
        this.id = id;
    }
    public ExCollege(String id, String collegenum, String name, String remark,  ExInstitution exInstitution, Set exStudents) {
       this.id = id;
       this.collegenum = collegenum;
       this.name = name;
       this.remark = remark;
       this.exInstitution = exInstitution;
       this.exStudents = exStudents;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCollegenum() {
        return this.collegenum;
    }
    
    public void setCollegenum(String collegenum) {
        this.collegenum = collegenum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    
    public Set getExStudents() {
        return this.exStudents;
    }
    
    public void setExStudents(Set exStudents) {
        this.exStudents = exStudents;
    }




}


