package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExStudentstatus generated by hbm2java
 */
@DataTransferObject
public class ExInstitutionstatus  implements java.io.Serializable {


     private String id;
     private Integer statusnum;
     private Integer indexnum;
     private String name;
     private Date starttime;
     private Date endtime;
     private String alterMessage;
     private String remarks;
     private String rolename;
     private Set exInstitutions = new HashSet(0);

    public ExInstitutionstatus() {
    }

	
    public ExInstitutionstatus(String id) {
        this.id = id;
    }
    public ExInstitutionstatus(String id, ExInstitution exInstitution, Integer statusnum,Integer indexnum, String name, Date starttime, Date endtime,String alterMessage, String remarks, Set exInstitutions,String rolename) {
       this.id = id;
       this.statusnum = statusnum;
       this.name = name;
       this.starttime = starttime;
       this.endtime = endtime;
       this.remarks = remarks;
       this.exInstitutions = exInstitutions;
       this.alterMessage=alterMessage;
       this.rolename=rolename;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getAlterMessage() {
        return this.alterMessage;
    }
    
    public void setAlterMessage(String alterMessage) {
        this.alterMessage = alterMessage;
    }
    public Integer getStatusnum() {
        return this.statusnum;
    }
    
    public void setStatusnum(Integer statusnum) {
        this.statusnum = statusnum;
    }
    
    public Integer getIndexnum() {
        return this.statusnum;
    }
    
    public void setIndexnum(Integer indexnum) {
        this.indexnum = indexnum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getExInstitutions() {
        return this.exInstitutions;
    }
    
    public void setExInstitutions(Set exInstitutions) {
        this.exInstitutions = exInstitutions;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    public String getRolename() {
        return this.rolename;
    }
}


