package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExInstitution generated by hbm2java
 */
@DataTransferObject
public class ExInstitution  implements java.io.Serializable {


     private String id;
     private ExInstitution higherInstitution;
     private String institutionnum;
     private ExInstitutionstatus institutionstatus;
     private String name;
     private String category;
     private String contact;
     private String remark;
     private String signupflag;
     private String checkscoreflag;
     private Set exCampuses = new HashSet(0);
     private Set exStudents = new HashSet(0);
     private Set exInstitutions = new HashSet(0);
     private Set exArrangements = new HashSet(0);
     private Set exSections = new HashSet(0);
     private Set exStudentstatuses = new HashSet(0);
     private Set exUsers = new HashSet(0);
     private Set exNewses = new HashSet(0);
     private Set exSupervisors = new HashSet(0);
     private Set exPhysicexamrooms = new HashSet(0);
     private Set exArrangeSupervisors = new HashSet(0);

    public ExInstitution() {
    }

	
    public ExInstitution(String id) {
        this.id = id;
    }
    public ExInstitution(String id, ExInstitution higherInstitution, String institutionnum, String name, String category, String contact, String remark, Set exCampuses, Set exStudents, Set exInstitutions, Set exArrangements, Set exSections, Set exStudentstatuses, Set exUsers, Set exNewses, Set exSupervisors, Set exPhysicexamrooms, Set exArrangeSupervisors,ExInstitutionstatus institutionstatus) {
       this.id = id;
       this.higherInstitution = higherInstitution;
       this.institutionnum = institutionnum;
       this.name = name;
       this.category = category;
       this.contact = contact;
       this.remark = remark;
       this.exCampuses = exCampuses;
       this.exStudents = exStudents;
       this.exInstitutions = exInstitutions;
       this.exArrangements = exArrangements;
       this.exSections = exSections;
       this.exStudentstatuses = exStudentstatuses;
       this.exUsers = exUsers;
       this.exNewses = exNewses;
       this.exSupervisors = exSupervisors;
       this.exPhysicexamrooms = exPhysicexamrooms;
       this.exArrangeSupervisors=exArrangeSupervisors;
       this.institutionstatus= institutionstatus;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExInstitution getHigherInstitution() {
        return this.higherInstitution;
    }
    
    public void setHigherInstitution(ExInstitution higherInstitution) {
        this.higherInstitution = higherInstitution;
    }
    public String getInstitutionnum() {
        return this.institutionnum;
    }
    
    public void setInstitutionnum(String institutionnum) {
        this.institutionnum = institutionnum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getExCampuses() {
        return this.exCampuses;
    }
    
    public void setExCampuses(Set exCampuses) {
        this.exCampuses = exCampuses;
    }
    public Set getExStudents() {
        return this.exStudents;
    }
    
    public void setExStudents(Set exStudents) {
        this.exStudents = exStudents;
    }
    public Set getExInstitutions() {
        return this.exInstitutions;
    }
    
    public void setExInstitutions(Set exInstitutions) {
        this.exInstitutions = exInstitutions;
    }

    public Set getExArrangements() {
        return this.exArrangements;
    }
    
    public void setExArrangements(Set exArrangements) {
        this.exArrangements = exArrangements;
    }
    public Set getExSections() {
        return this.exSections;
    }
    
    public void setExSections(Set exSections) {
        this.exSections = exSections;
    }
    public Set getExStudentstatuses() {
        return this.exStudentstatuses;
    }
    
    public void setExStudentstatuses(Set exStudentstatuses) {
        this.exStudentstatuses = exStudentstatuses;
    }
    public Set getExUsers() {
        return this.exUsers;
    }
    
    public void setExUsers(Set exUsers) {
        this.exUsers = exUsers;
    }
    public Set getExNewses() {
        return this.exNewses;
    }
    
    public void setExNewses(Set exNewses) {
        this.exNewses = exNewses;
    }
    public Set getExSupervisors() {
        return this.exSupervisors;
    }
    
    public void setExSupervisors(Set exSupervisors) {
        this.exSupervisors = exSupervisors;
    }
    public Set getExPhysicexamrooms() {
        return this.exPhysicexamrooms;
    }
    
    public void setExPhysicexamrooms(Set exPhysicexamrooms) {
        this.exPhysicexamrooms = exPhysicexamrooms;
    }
    
    public Set getExArrangeSupervisors(){
    	return this.exArrangeSupervisors;
    }
    public void setExArrangeSupervisors(Set exArrangeSupervisors){
    	this.exArrangeSupervisors=exArrangeSupervisors;
    }

	
	public ExInstitutionstatus getInstitutionstatus(){
		return this.institutionstatus;
	}
	
	public void setInstitutionstatus(ExInstitutionstatus institutionstatus){
		this.institutionstatus=institutionstatus;
	}


	public String getSignupflag() {
		return signupflag;
	}


	public void setSignupflag(String signupflag) {
		this.signupflag = signupflag;
	}


	public String getCheckscoreflag() {
		return checkscoreflag;
	}


	public void setCheckscoreflag(String checkscoreflag) {
		this.checkscoreflag = checkscoreflag;
	}




}