package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExLanguage generated by hbm2java
 */
@DataTransferObject
public class ExLanguage  implements java.io.Serializable {


     private String id;
     private String languagenum;
     private String name;
     private String theoryflag;
     private String operateflag;
     private Integer theorylength;
     private Integer operatelength;
     private Set exStudents = new HashSet(0);
     private Set exArrangements = new HashSet(0);

    public ExLanguage() {
    }

	
    public ExLanguage(String id) {
        this.id = id;
    }
    public ExLanguage(String id, String languagenum, String name, String theoryflag, String operateflag, Integer theorylength, Integer operatelength, Set exStudents, Set exArrangements) {
       this.id = id;
       this.languagenum = languagenum;
       this.name = name;
       this.theoryflag = theoryflag;
       this.operateflag = operateflag;
       this.theorylength = theorylength;
       this.operatelength = operatelength;
       this.exStudents = exStudents;
       this.exArrangements = exArrangements;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getLanguagenum() {
        return this.languagenum;
    }
    
    public void setLanguagenum(String languagenum) {
        this.languagenum = languagenum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTheoryflag() {
        return this.theoryflag;
    }
    
    public void setTheoryflag(String theoryflag) {
        this.theoryflag = theoryflag;
    }
    public String getOperateflag() {
        return this.operateflag;
    }
    
    public void setOperateflag(String operateflag) {
        this.operateflag = operateflag;
    }
    public Integer getTheorylength() {
        return this.theorylength;
    }
    
    public void setTheorylength(Integer theorylength) {
        this.theorylength = theorylength;
    }
    public Integer getOperatelength() {
        return this.operatelength;
    }
    
    public void setOperatelength(Integer operatelength) {
        this.operatelength = operatelength;
    }
    public Set getExStudents() {
        return this.exStudents;
    }
    
    public void setExStudents(Set exStudents) {
        this.exStudents = exStudents;
    }
    public Set getExArrangements() {
        return this.exArrangements;
    }
    
    public void setExArrangements(Set exArrangements) {
        this.exArrangements = exArrangements;
    }




}


