package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExMainmenu generated by hbm2java
 */
@DataTransferObject
public class ExMainmenu  implements java.io.Serializable {


     private String id;
     private ExRole exRole;
     private ExMainmenu exMainmenu;
     private String menuid;
     private String showname;
     private String onclickscript;
     private Integer sortindex;
     private Set exMainmenus = new HashSet(0);

    public ExMainmenu() {
    }

	
    public ExMainmenu(String id, String menuid) {
        this.id = id;
        this.menuid = menuid;
    }
    public ExMainmenu(String id, ExRole exRole, ExMainmenu exMainmenu, String menuid, String showname, String onclickscript, Integer sortindex, Set exMainmenus) {
       this.id = id;
       this.exRole = exRole;
       this.exMainmenu = exMainmenu;
       this.menuid = menuid;
       this.showname = showname;
       this.onclickscript = onclickscript;
       this.sortindex = sortindex;
       this.exMainmenus = exMainmenus;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExRole getExRole() {
        return this.exRole;
    }
    
    public void setExRole(ExRole exRole) {
        this.exRole = exRole;
    }
    public ExMainmenu getExMainmenu() {
        return this.exMainmenu;
    }
    
    public void setExMainmenu(ExMainmenu exMainmenu) {
        this.exMainmenu = exMainmenu;
    }
    public String getMenuid() {
        return this.menuid;
    }
    
    public void setMenuid(String menuid) {
        this.menuid = menuid;
    }
    public String getShowname() {
        return this.showname;
    }
    
    public void setShowname(String showname) {
        this.showname = showname;
    }
    public String getOnclickscript() {
        return this.onclickscript;
    }
    
    public void setOnclickscript(String onclickscript) {
        this.onclickscript = onclickscript;
    }
    public Integer getSortindex() {
        return this.sortindex;
    }
    
    public void setSortindex(Integer sortindex) {
        this.sortindex = sortindex;
    }
    public Set getExMainmenus() {
        return this.exMainmenus;
    }
    
    public void setExMainmenus(Set exMainmenus) {
        this.exMainmenus = exMainmenus;
    }




}


