package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExNews generated by hbm2java
 */
@DataTransferObject
public class ExNews  implements java.io.Serializable {


     private String id;
     private ExInstitution exInstitution;
     private String title;
     private String publisher;
     private String content;
     private Date begindate;
     private Date enddate;

    public ExNews() {
    }

	
    public ExNews(String id) {
        this.id = id;
    }
    public ExNews(String id, ExInstitution exInstitution, String title, String publisher, String content, Date begindate, Date enddate) {
       this.id = id;
       this.exInstitution = exInstitution;
       this.title = title;
       this.publisher = publisher;
       this.content = content;
       this.begindate = begindate;
       this.enddate = enddate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getBegindate() {
        return this.begindate;
    }
    
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }




}


