package cn.hdu.examsignup.model;

import org.directwebremoting.annotations.DataTransferObject;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1



/**
 * ExParameter generated by hbm2java
 */
@DataTransferObject
public class ExParameter  implements java.io.Serializable {


     private String id;
     private String name;
     private String paramvalue;
     private String paramtype;
     private String enumvalue;
     private String memo;

    public ExParameter() {
    }

	
    public ExParameter(String id) {
        this.id = id;
    }
    public ExParameter(String id, String name, String paramvalue, String paramtype, String enumvalue, String memo) {
       this.id = id;
       this.name = name;
       this.paramvalue = paramvalue;
       this.paramtype = paramtype;
       this.enumvalue = enumvalue;
       this.memo = memo;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getParamvalue() {
        return this.paramvalue;
    }
    
    public void setParamvalue(String paramvalue) {
        this.paramvalue = paramvalue;
    }
    public String getParamtype() {
        return this.paramtype;
    }
    
    public void setParamtype(String paramtype) {
        this.paramtype = paramtype;
    }
    public String getEnumvalue() {
        return this.enumvalue;
    }
    
    public void setEnumvalue(String enumvalue) {
        this.enumvalue = enumvalue;
    }
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }




}


