package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExPhysicexamroom generated by hbm2java
 */
@DataTransferObject
public class ExPhysicexamroom  implements java.io.Serializable {


     private String id;
     private ExInstitution exInstitution;
     private ExCampus exCampus;
     private String roomlocation;
     private Integer capacity;
     private String theoryflag;
     private String operateflag;
     private Set exArrangements = new HashSet(0);

    public ExPhysicexamroom() {
    }

	
    public ExPhysicexamroom(String id) {
        this.id = id;
    }
    public ExPhysicexamroom(String id, ExInstitution exInstitution, ExCampus exCampus, String roomlocation, Integer capacity, String theoryflag, String operateflag, Set exArrangements) {
       this.id = id;
       this.exInstitution = exInstitution;
       this.exCampus = exCampus;
       this.roomlocation = roomlocation;
       this.capacity = capacity;
       this.theoryflag = theoryflag;
       this.operateflag = operateflag;
       this.exArrangements = exArrangements;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    public ExCampus getExCampus() {
        return this.exCampus;
    }
    
    public void setExCampus(ExCampus exCampus) {
        this.exCampus = exCampus;
    }
    public String getRoomlocation() {
        return this.roomlocation;
    }
    
    public void setRoomlocation(String roomlocation) {
        this.roomlocation = roomlocation;
    }
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
    public String getTheoryflag() {
        return this.theoryflag;
    }
    
    public void setTheoryflag(String theoryflag) {
        this.theoryflag = theoryflag;
    }
    public String getOperateflag() {
        return this.operateflag;
    }
    
    public void setOperateflag(String operateflag) {
        this.operateflag = operateflag;
    }
    public Set getExArrangements() {
        return this.exArrangements;
    }
    
    public void setExArrangements(Set exArrangements) {
        this.exArrangements = exArrangements;
    }




}


