package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExProfession generated by hbm2java
 */
@DataTransferObject
public class ExProfession  implements java.io.Serializable {


     private String id;
     private String professionnum;
     private String name;
     private String remark;
     private String institutionid;
     private Set exStudents = new HashSet(0);

    public ExProfession() {
    }

	
    public ExProfession(String id) {
        this.id = id;
    }
    public ExProfession(String id, String professionnum, String name, String remark, String institutionid, Set exStudents) {
       this.id = id;
       this.professionnum = professionnum;
       this.name = name;
       this.remark = remark;
       this.institutionid = institutionid;
       this.exStudents = exStudents;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getProfessionnum() {
        return this.professionnum;
    }
    
    public void setProfessionnum(String professionnum) {
        this.professionnum = professionnum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public String getInstitutionid() {
        return this.institutionid;
    }
    
    public void setInstitutionid(String institutionid) {
        this.institutionid = institutionid;
    }
    public Set getExStudents() {
        return this.exStudents;
    }
    
    public void setExStudents(Set exStudents) {
        this.exStudents = exStudents;
    }




}


