package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExRole generated by hbm2java
 */
@DataTransferObject
public class ExRole  implements java.io.Serializable {


     private String id;
     private Integer rolenum;
     private String name;
     private String remark;
     private Set exMainmenus = new HashSet(0);
     private Set exUsers = new HashSet(0);

    public ExRole() {
    }

	
    public ExRole(String id) {
        this.id = id;
    }
    public ExRole(String id, Integer rolenum, String name, String remark, Set exMainmenus, Set exUsers) {
       this.id = id;
       this.rolenum = rolenum;
       this.name = name;
       this.remark = remark;
       this.exMainmenus = exMainmenus;
       this.exUsers = exUsers;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getRolenum() {
        return this.rolenum;
    }
    
    public void setRolenum(Integer rolenum) {
        this.rolenum = rolenum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getExMainmenus() {
        return this.exMainmenus;
    }
    
    public void setExMainmenus(Set exMainmenus) {
        this.exMainmenus = exMainmenus;
    }
    public Set getExUsers() {
        return this.exUsers;
    }
    
    public void setExUsers(Set exUsers) {
        this.exUsers = exUsers;
    }




}


