package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExStudentstatus generated by hbm2java
 */
@DataTransferObject
public class ExStudentstatus  implements java.io.Serializable {


     private String id;
     private ExInstitution exInstitution;
     private Integer statusnum;
     private String name;
     private Date starttime;
     private Date endtime;
     private String remarks;
     private Set exStudents = new HashSet(0);

    public ExStudentstatus() {
    }

	
    public ExStudentstatus(String id) {
        this.id = id;
    }
    public ExStudentstatus(String id, ExInstitution exInstitution, Integer statusnum, String name, Date starttime, Date endtime, String remarks, Set exStudents) {
       this.id = id;
       this.exInstitution = exInstitution;
       this.statusnum = statusnum;
       this.name = name;
       this.starttime = starttime;
       this.endtime = endtime;
       this.remarks = remarks;
       this.exStudents = exStudents;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    public Integer getStatusnum() {
        return this.statusnum;
    }
    
    public void setStatusnum(Integer statusnum) {
        this.statusnum = statusnum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getExStudents() {
        return this.exStudents;
    }
    
    public void setExStudents(Set exStudents) {
        this.exStudents = exStudents;
    }




}


