package cn.hdu.examsignup.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;


import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExStudent generated by hbm2java
 */
@DataTransferObject
public class ExStudent  implements java.io.Serializable {

     private String id;
     private ExInstitution exInstitution;
     private ExLanguage exLanguage;
     private ExProfession exProfession;
     private ExArrangement exArrangementByOperatearrangeid;
     private ExArrangement exArrangementByTheoryarrangeid;
     private ExCollege exCollege;
     private ExStudentstatus exStudentstatus;
     private ExCampus exCampus;
     private String name;
     private String password;
     private String sex;
     private String studentnum;
     private String idnum;
     private String ethno;
     private String examnum;
     private String exambatch;
     private String grade;
     private String classnum;
     private String lengthofyear;
     private String studentcategory;
     private String paied;
     private BigDecimal score;
     private BigDecimal newscore;
     private String theoryabsent;
     private String operateabsent;
     private String theoryfraud;
     private String operatefraud;
     private String remark;
     private Integer operateseat;
     
     public ExStudent() {
     }

	
    public ExStudent(String id) {
        this.id = id;
    }
    public ExStudent(String id, ExInstitution exInstitution, ExLanguage exLanguage, ExProfession exProfession, ExArrangement exArrangementByOperatearrangeid, ExArrangement exArrangementByTheoryarrangeid, ExCollege exCollege, ExStudentstatus exStudentstatus, ExCampus exCampus, String name, String password, String sex, String studentnum, String idnum, String ethno, String examnum, String exambatch, String grade, String classnum, String lengthofyear, String studentcategory, String paied, BigDecimal score, BigDecimal newscore,String theoryabsent, String operateabsent, String theoryfraud, String operatefraud) {
       this.id = id;
       this.exInstitution = exInstitution;
       this.exLanguage = exLanguage;
       this.exProfession = exProfession;
       this.exArrangementByOperatearrangeid = exArrangementByOperatearrangeid;
       this.exArrangementByTheoryarrangeid = exArrangementByTheoryarrangeid;
       this.exCollege = exCollege;
       this.exStudentstatus = exStudentstatus;
       this.exCampus = exCampus;
       this.name = name;
       this.password = password;
       this.sex = sex;
       this.studentnum = studentnum;
       this.idnum = idnum;
       this.ethno = ethno;
       this.examnum = examnum;
       this.exambatch = exambatch;
       this.grade = grade;
       this.classnum = classnum;
       this.lengthofyear = lengthofyear;
       this.studentcategory = studentcategory;
       this.paied = paied;
       this.score = score;
       this.theoryabsent = theoryabsent;
       this.operateabsent = operateabsent;
       this.theoryfraud = theoryfraud;
       this.operatefraud = operatefraud;
       this.newscore = newscore;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    public ExLanguage getExLanguage() {
        return this.exLanguage;
    }
    
    public void setExLanguage(ExLanguage exLanguage) {
        this.exLanguage = exLanguage;
    }
    public ExProfession getExProfession() {
        return this.exProfession;
    }
    
    public void setExProfession(ExProfession exProfession) {
        this.exProfession = exProfession;
    }
    public ExArrangement getExArrangementByOperatearrangeid() {
        return this.exArrangementByOperatearrangeid;
    }
    
    public void setExArrangementByOperatearrangeid(ExArrangement exArrangementByOperatearrangeid) {
        this.exArrangementByOperatearrangeid = exArrangementByOperatearrangeid;
    }
    public ExArrangement getExArrangementByTheoryarrangeid() {
        return this.exArrangementByTheoryarrangeid;
    }
    
    public void setExArrangementByTheoryarrangeid(ExArrangement exArrangementByTheoryarrangeid) {
        this.exArrangementByTheoryarrangeid = exArrangementByTheoryarrangeid;
    }
    public ExCollege getExCollege() {
        return this.exCollege;
    }
    
    public void setExCollege(ExCollege exCollege) {
        this.exCollege = exCollege;
    }
    public ExStudentstatus getExStudentstatus() {
        return this.exStudentstatus;
    }
    
    public void setExStudentstatus(ExStudentstatus exStudentstatus) {
        this.exStudentstatus = exStudentstatus;
    }
    public ExCampus getExCampus() {
        return this.exCampus;
    }
    
    public void setExCampus(ExCampus exCampus) {
        this.exCampus = exCampus;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getStudentnum() {
        return this.studentnum;
    }
    
    public void setStudentnum(String studentnum) {
        this.studentnum = studentnum;
    }
    public String getIdnum() {
        return this.idnum;
    }
    
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }
    public String getEthno() {
        return this.ethno;
    }
    
    public void setEthno(String ethno) {
        this.ethno = ethno;
    }
    public String getExamnum() {
        return this.examnum;
    }
    
    public void setExamnum(String examnum) {
        this.examnum = examnum;
    }
    public String getExambatch() {
        return this.exambatch;
    }
    
    public void setExambatch(String exambatch) {
        this.exambatch = exambatch;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public String getClassnum() {
        return this.classnum;
    }
    
    public void setClassnum(String classnum) {
        this.classnum = classnum;
    }
    public String getLengthofyear() {
        return this.lengthofyear;
    }
    
    public void setLengthofyear(String lengthofyear) {
        this.lengthofyear = lengthofyear;
    }
    public String getStudentcategory() {
        return this.studentcategory;
    }
    
    public void setStudentcategory(String studentcategory) {
        this.studentcategory = studentcategory;
    }
    public String getPaied() {
        return this.paied;
    }
    
    public void setPaied(String paied) {
        this.paied = paied;
    }
    public BigDecimal getScore() {
        return this.score;
    }
    
    public void setScore(BigDecimal score) {
        this.score = score;
    }
    public String getTheoryabsent() {
        return this.theoryabsent;
    }
    
    public void setTheoryabsent(String theoryabsent) {
        this.theoryabsent = theoryabsent;
    }
    public String getOperateabsent() {
        return this.operateabsent;
    }
    
    public void setOperateabsent(String operateabsent) {
        this.operateabsent = operateabsent;
    }
    public String getTheoryfraud() {
        return this.theoryfraud;
    }
    
    public void setTheoryfraud(String theoryfraud) {
        this.theoryfraud = theoryfraud;
    }
    public String getOperatefraud() {
        return this.operatefraud;
    }
    
    public void setOperatefraud(String operatefraud) {
        this.operatefraud = operatefraud;
    }


	public BigDecimal getNewscore() {
		return newscore;
	}


	public void setNewscore(BigDecimal newscore) {
		this.newscore = newscore;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	public Integer getOperateseat() {
		return operateseat;
	}


	public void setOperateseat(Integer operateseat) {
		this.operateseat = operateseat;
	}
}


