package cn.hdu.examsignup.model;

import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1



/**
 * ExSupervisor generated by hbm2java
 */
@DataTransferObject
public class ExSupervisor  implements java.io.Serializable {


    private String id;
    private ExInstitution exInstitution;
    private ExCollege exCollege;
    private String name;
    private String supervisornum;
    private String contact;
    private Set exArrangeSupervisors = new HashSet(0);
	private String theoryflag;
    private String operateflag;
    private String primaryflag;
    public String getTheoryflag() {
		return theoryflag;
	}
	public void setTheoryflag(String theoryflag) {
		this.theoryflag = theoryflag;
	}
	
	public String getOperateflag() {
		return operateflag;
	}


	public void setOperateflag(String operateflag) {
		this.operateflag = operateflag;
	}


    public ExSupervisor() {
    }

	
    public ExSupervisor(String id) {
        this.id = id;
    }
    public ExSupervisor(String id,  ExInstitution exInstitution, ExCollege exCollege, String name, String supervisornum, String contact,
    		String theoryflag,String operateflag ,Set exArrangeSupervisors,String primaryflag) {
       this.id = id;
       this.exInstitution = exInstitution;
       this.exCollege = exCollege;
       this.name = name;
       this.supervisornum = supervisornum;
       this.contact = contact;
       this.exArrangeSupervisors=exArrangeSupervisors;
       this.operateflag = operateflag;
       this.theoryflag = theoryflag;
       this.primaryflag = primaryflag;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public ExInstitution getExInstitution() {
        return this.exInstitution;
    }
    
    public void setExInstitution(ExInstitution exInstitution) {
        this.exInstitution = exInstitution;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSupervisornum() {
        return this.supervisornum;
    }
    
    public void setSupervisornum(String supervisornum) {
        this.supervisornum = supervisornum;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    
    public Set getExArrangeSupervisors(){
    	return this.exArrangeSupervisors;
    }
    public Set setExArrangeSupervisors(Set exArrangeSupervisors){
    	return this.exArrangeSupervisors;
    }
	public ExCollege getExCollege() {
		return exCollege;
	}
	public void setExCollege(ExCollege exCollege) {
		this.exCollege = exCollege;
	}
	public String getPrimaryflag() {
		return primaryflag;
	}
	public void setPrimaryflag(String primaryflag) {
		this.primaryflag = primaryflag;
	}
    
}